# Generated by Django 3.2.7 on 2021-09-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(help_text='Hold ctrl to pick multiple tags!', to='blog.Tag'),
        ),
    ]
